codecov:
  branch: devel

coverage:
  status:
    project:
      default:
        target: 90
        threshold: 0.09
  notify:
    # Codecov notification on Slack  
    slack:
      default:
        url: "secret:ukCTVFHMOQS3tIJ9ZTuG8cPhtDktijRlJcHFHKjihyC2A6TVqre85t26G9jpXt6+fiMPpEP+m5d+RKPWq7kb2iiCn92KBl5AtYyZoHVijG7fBpxLTAX3/ZkY5NkBSGnBVrj+p5aGb/TfLn/3iUzOpNtFFGixJu5nWiGAeWYae+0="

#Only post coverage comment if coverage changes
comment:
  require_changes: yes
