sudo: required
dist: xenial

language: python
python:
  - "3.7"

branches:
  only:
    - devel
    - travis

before_install:
  # print the distro information
  - lsb_release -a
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran

  # Here we just install Miniconda, which you shouldn't have to change.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export F90=gfortran
  - conda update --yes conda

install:
  - conda create --yes --name rem3d python=$TRAVIS_PYTHON_VERSION
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - source activate rem3d
  - conda install --yes netcdf4 basemap basemap-data-hires
  - pip install python-slugify
  - pip install codecov
    
script:
  # Running pip install -e . --user directly causes errors
  # Refer https://jeetblogs.org/post/strange-uninstall-failures-when-running-pip-install-in-editable-mode/
  - cd ..
  - pip install -e rem3d --user
  # Add the required command for testing here
  - cd rem3d/examples/Tests
  - python grab_server_data.py
  - if diff ./S362ANI+M.vs.5.epix ./Outputs/S362ANI+M.vs.5.epix ; then
      echo "Build successful";
    else
      echo "Build failed";
      exit 1;
    fi
    
after_success:
  - codecov -t 780b4864-10db-46f6-8118-3a93665c8546