name: avni-devel
channels:
  - default
  - conda-forge
dependencies:
  - astropy=4.0.1.post1
  - basemap=1.2.2
  - bokeh=2.1.1
  - netcdf4=1.5.3
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.5.0
  - configobj=5.0.6
  - cryptography=2.9.2
  - dash=1.13.3
  - dash-core-components=1.10.1
  - dash-html-components=1.0.3
  - dash-renderer=1.5.0
  - dash-table=4.8.1
  - dask=2.21.0
  - dask-core=2.21.0
  - datashader=0.11.0
  - descartes=1.1.0
  - fiona=1.8.13
  - flask=1.1.2
  - flask-restful=0.3.8
  - fortranformat=0.2.5
  - geopandas=0.8.1
  - gunicorn=20.0.4
  - h5py=2.10.0
  - joblib=1.1.0
  - matplotlib=3.3.0
  - mysql-connector-python=8.0.20
  - numpydoc=1.1.0
  - numba=0.48.0
  - obspy=1.2.2
  - pillow=7.2.0
  - pint=0.14
  - plotly=4.9.0
  - progressbar=2.5
  - pymongo=3.10.1
  - pyshp=2.1.0
  - pyshtools
  - pytables=3.6.1
  - pyyaml=5.3.1
  - recommonmark=0.7.1
  - scipy=1.2.1
  - shapely=1.7.0
  - sphinx=4.3.0
  - sphinx_rtd_theme=1.0.0
  - sphinxcontrib=1.0
  - sphinxcontrib-bibtex=2.4.1
  - sqlalchemy=1.3.18
  - sqlite=3.32.3
  - urllib3=1.24.3
  - xarray=0.16.0
