name: avni-applets
channels:
  - conda-forge
dependencies:
  - bokeh=2.1.1
  - netcdf4=1.5.3
  - click=7.1.2
  - cloudpickle=1.5.0
  - cryptography=2.9.2
  - dash=1.13.3
  - dash-core-components=1.10.1
  - dash-html-components=1.0.3
  - dash-renderer=1.5.0
  - dash-table=4.8.1
  - dask=2.21.0
  - dask-core=2.21.0
  - datashader=0.11.0
  - descartes=1.1.0
  - fiona=1.8.13
  - flask=1.1.2
  - flask-restful=0.3.8
  - fortranformat=0.2.5
  - geopandas=0.8.1
  - gunicorn=20.0.4
  - h5py=2.10.0
  - matplotlib=3.3.0
  - mysql-connector-python=8.0.20
  - numba=0.48.0
  - obspy=1.2.2
  - pillow=7.2.0
  - pint=0.14
  - plotly=4.9.0
  - progressbar=2.5
  - pymongo=3.10.1
  - pyshp=2.1.0
  - pytables=3.6.1
  - pyyaml=5.3.1
  - scipy=1.2.1
  - shapely=1.7.0
  - sqlalchemy=1.3.18
  - sqlite=3.32.3
  - astropy=4.0.1.post1
  - configobj=5.0.6
  - xarray=0.16.0
