name: avni-doc
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - ipython
  - numpydoc
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - sphinx-sitemap
  - pydata_sphinx_theme
  - sphinxcontrib
  - sphinxcontrib-apidoc
  - sphinxcontrib-bibtex
  - sphinx-gallery
  - pyshtools
  - basemap
