name: Build docs on PR
on: push
jobs:
  build-and-preview:
   runs-on: ubuntu-latest
   steps:
      - name: Requirements
        run: conda config --append channels conda-forge
         && sudo apt-get install doxygen python3-sphinx
         && pip3 install sphinx_rtd_theme
         && pip3 install sphinx-sitemap
         && pip3 install numpydoc
         && pip3 install sphinxcontrib-bibtex
#    runs-on: macos-latest
#    steps:
#      - name: Requirements
#        run: brew install doxygen
#          && brew install sphinx-doc
#          && pip3 install sphinx-rtd-theme
#          && pip3 install breathe
#          && pip3 install sphinx-sitemap
#          && pip3 install numpydoc
#          && pip3 install sphinxcontrib-bibtex
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build docs
        run: cd docs
          && make html
          && cd _build/html
          && touch .nojekyll
          && mkdir ../../../public
          && cp -r * ../../../public
      - name: Run .travis.yml build script
        uses: ktomk/run-travis-yml@v1
        with:
          file: .travis.yml
          steps: |
            install
            script
          allow-failure: false
        env:
          TRAVIS_PHP_VERSION: ${{ matrix.php-versions }}
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVNI_EC064 }}'
          projectId: avni-ec064
          channelId: 'pr-${{ github.event.number }}'
          expires: 7d
