name: Build docs on PR
on: push
jobs:
  build-html-and-preview:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/devel'
   steps:
      - name: Requirements
        run: conda config --append channels conda-forge
         && sudo apt-get install doxygen python3-sphinx
         && pip3 install sphinx_rtd_theme
         && pip3 install sphinx-sitemap
         && pip3 install numpydoc
         && pip3 install -U Sphinx
         && pip3 install sphinxcontrib-bibtex
         && pip3 install numpy pygments
      - name: Checkout repo
        uses: actions/checkout@v2

#     Caching based on https://stackoverflow.com/a/57958803
      - name: Cache Tex dependencies
        id: cache-tex
        uses: actions/cache@v3
        with:
          path:  |
            /tmp/texlive
            $HOME/.texlive
          key: ${{ runner.os }}-tex-cache-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-tex-cache-${{ env.cache-name }}-
            ${{ runner.os }}-tex-cache-

#       Install TexLive
# https://github.com/PHPirates/travis-ci-latex-pdf#instructions-for-building-with-pdflatexlualatexlatexmkxelatextexliveonflyetc-and-tex-live
      - name: Install Tex dependencies
        run: |
          source docs/texlive/texlive_install.sh
          echo "/tmp/texlive/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Build html docs
        run: cd docs
          && make html
          && cd _build/html
          && mkdir ../../../public
          && cp -r * ../../../public
          && cd ../../..

      - name: Build pdf docs
        run: cd docs
          && make latex
          && cd _build/latex
          && texliveonfly AVNI.tex
          && ls /tmp/texlive/bin/x86_64-linux
          && make
          && cd ../../..

#     Cache npm modules
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-

#     Rsync with SSH
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_DWAR }}
          known_hosts: unnecessary
#      - name: Adding Known Hosts
#        run: ssh-keyscan -H ${{ secrets.SSH_HOST_DWAR }} >> ~/.ssh/known_hosts
#      - name: Deploy with rsync
#        run: rsync -avz docs/_build/html/* ${{ secrets.SSH_USER_DWAR }}@${{ secrets.SSH_HOST_DWAR }}:/home/pm5113/actions/


#     Deploy to Firebase
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVNI_EC064 }}'
          projectId: avni-ec064
          channelId: 'pr-${{ github.event.number }}'
          expires: 7d


#     Slack notification
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n${{ github.event.number }}\nTemporary ReadtheDocs: https://avni-ec064--pr-${{ github.event.number }}.web.app'"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK