name: Build docs on PR
on: push
jobs:
  build-and-preview:
   runs-on: ubuntu-latest
   steps:
      - name: Requirements
        run: conda config --append channels conda-forge
         && sudo apt-get install doxygen python3-sphinx
         && conda install sphinx_rtd_theme
         && conda install sphinx-sitemap
         && conda install sphinxcontrib
         && pip3 install numpydoc
         && conda install sphinxcontrib-bibtex
#    runs-on: macos-latest
#    steps:
#      - name: Requirements
#        run: brew install doxygen
#          && brew install sphinx-doc
#          && pip3 install sphinx-rtd-theme
#          && pip3 install breathe
#          && pip3 install sphinx-sitemap
#          && pip3 install numpydoc
#          && pip3 install sphinxcontrib-bibtex
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build docs
        run: cd docs
          && make html
          && cd _build/html
          && touch .nojekyll
          && mkdir ../../../public
          && cp -r * ../../../public
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AVNI_EC064 }}'
          projectId: avni-ec064
          channelId: 'pr-${{ github.event.number }}'
          expires: 7d
